import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header/Header'
import Footer from '../../components/Footer/Footer'
const ProfilePage = () => {
  return (
    <>
        <Head>
        <title>Vinci Gallery</title>
        <meta name="description" content="Generated by Vinci Gallery" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
          
        <Footer />
    </>
  )
}
export default ProfilePage
