import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
const ProfilePage = () => {
  return (
    <>
        <Head>
        <title>Vinci Gallery</title>
        <meta name="description" content="Generated by Vinci Gallery" />
        <Link rel="icon" href="/favicon.ico" />
        </Head>
    </>
  )
}
export default ProfilePage
