
import React from 'react'
import Head from 'next/head'
import { Typography, Box, Container, Button  } from '@mui/material'
import Link from 'next/link'
export default function Landing() {
  return (
    <>
      <Head>
          <title>حدیث غربت</title>
          <meta name="description" content="Generated by حدیث غربت" />
          
      </Head>
      <Container className='home-container' sx={{px:'2rem' , textAlign:'right '}}   maxWidth="xl" >
            <Container sx={{display:'flex',justifyContent:'space-between',p:'2rem'}}   maxWidth="xl" >
              <Box  sx={{width:{md:'40%',sm:'100%'}}} className='color-white'>
                <Typography variant='h1' component={'h1'}  > حدیث غربت</Typography>
                <Typography variant='h2' component={'h1'} gutterBottom> اَللّهُمَّ صَلِّ عَلی فاطِمَة وَ اَبیها</Typography>
                <Typography variant='p'>
                  إنَّ اللّهَ یَغْفِرُ الذُّنُوبَ جَمیعا وَلایُبالی. (تفسیر التّبیان:ج9، ص37، س16) 
                      <br/>
                      همانا خداوند متعال تمامی گناهان بندگانش را می آمرزد و از کسی باکی نخواهد داشت. 
                      <br/>
                      إلهی وَ سَیِّدی ، اءسْئَلُکَ بِالَّذینَ اصْطَفَیْتَهُمْ، وَ بِبُکاءِ وَلَدَیَّ فی مُفارِقَتی اَنْ تَغْفِرَ لِعُصاةِ شیعَتی ، وَشیعَةِ ذُرّیتَی .(کوکب الدّریّ:ج 1، ص 254) 
                      <br/>
                      خداوندا، به حقّ اولیاء و مقرّبانی که آنها را برگزیده ای، و به گریه فرزندانم پس از مرگ و جدائی من با ایشان، از تو می خواهم گناه خطاکاران شیعیان و پیروان ما را ببخشی.</Typography>
                      <br/>
                      ( حضرت زهرا سلام الله علیها)
                      <br/>
                      <br/>
                      <br/>
                      ** جهت رزرو صندلی در تئاتر حدیث غربت لطفا روی رزرو صندلی کلیک کنید ** 
                <Box mt={1}>
                  <Link href='/reserve'> 
                    <a>   <Button variant='contained'  size='large'  sx={{mt:3}}>ررزو صندلی  </Button></a>
                 </Link>
                 
                </Box>
              </Box>
            </Container>
      </Container>
     </>
)
}

