export const EVENT_DAYS= [
    {  text:'شنبه 26  دی ماه',
        id:'0',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'یکشنبه 27 دی ماه',
        id:'1',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'دوشنبه 28 دی ماه',
        id:'2',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'سه شنبه 29 دی ماه',
        id:'3',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'چهارشنبه 30 دی ماه',
        id:'4',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
   },
   {
    text:'پنجشنبه 1 دی ماه',
    id:'5',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
{
    text:'جمعه 2 دی ماه',
    id:'6',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
{
    text:'شنبه 3 دی ماه',
    id:'7',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
{
    text:'یکشنبه 4 دی ماه',
    id:'8',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
{
    text:'دوشنبه 5 دی ماه',
    id:'9',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
{
    text:'سه شنبه 6 دی ماه',
    id:'10',
    femaleCount:0,
    maleCount:0,
    femaleCheckBox:false,
    maleCheckBox:false,
},
 
]