export const EVENT_DAYS= [
    {  text:'شنبه',
        id:'saturday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'یکشنبه',
        id:'sunday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'دو شنبه',
        id:'monday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'سه شنبه',
        id:'thursday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'چهارشنبه',
        id:'wednesday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
   },
]