export const EVENT_DAYS= [
    {  text:'شنبه 26  دی ماه',
        id:'saturday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'یکشنبه 27 دی ماه',
        id:'sunday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'دو شننبه 28 دی ماه',
        id:'monday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'سه شنبه 29 دی ماه',
        id:'thursday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
    },{
        text:'تا سه شنبه 6 دی  ماه',
        id:'wednesday',
        femaleCount:0,
        maleCount:0,
        femaleCheckBox:false,
        maleCheckBox:false,
   },
]